"""Reuse the published fonts distributions, or report that the version is new.

The core package and the fonts companion package release on separate contracts
(issue #15, D1). A core release that changes nothing in the fonts data must not
rebuild and republish the fonts package: PyPI rejects an upload whose filename
already exists, a rebuild is a different file with different hashes, and
`skip-existing` would hide the collision instead of surfacing it. So the build
job asks this script one question before it builds anything: is the fonts
version declared by the tagged commit already on the index?

- A 404 for that exact `project/version` is the only answer that means *new*.
  Nothing is downloaded, nothing is written, and the workflow builds and
  publishes the fonts package as it always did.
- Any other answer means the version is published, so the release must reuse
  the **original files** - the wheel and the sdist the index recorded. Both are
  downloaded over HTTPS, checked against the SHA-256 and the size in the JSON
  response, and only then placed in the output directory. The fonts upload job
  does not run.
- Anything else fails closed: a transient or 5xx answer, a response that is not
  JSON or has no `urls`, a release carrying anything other than exactly one
  wheel and one sdist for that project and version, a file whose URL is not
  HTTPS or does not name its own filename, or a download whose bytes do not
  match the recorded digest.

A reused version is only legitimate when the tagged commit's package source is
the source that produced the published files. So the downloaded sdist's payload
is compared, file by file and byte for byte, with `packages/textflowkit-fonts`:
a changed package with an unbumped version would make the checkout claim
content the published files do not have. A difference stops the release and asks
for a fonts version bump instead.

The comparison is against the published sdist rather than against a tag named
after the fonts version: the two versions are independent, so a fonts release
need not have a tag named `v<fonts-version>`, and treating a missing tag as
"verified" would be worse than useless. The published sdist is the same evidence
class as the tag's tree and strictly stronger.

`--version` overrides the version read from the package's `pyproject.toml`, and
`--github-output` appends `fonts_mode=<new|reuse>` for the workflow job to
publish to later jobs. The file transport is injectable so the tests never
touch the network.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
import tarfile
import tempfile
import urllib.error
import urllib.parse
import urllib.request
import zipfile
from dataclasses import dataclass
from pathlib import Path

DEFAULT_PROJECT = "textflowkit-fonts"
DEFAULT_PACKAGE_DIR = "packages/textflowkit-fonts"
DEFAULT_OUT_DIR = "dist/fonts"
DEFAULT_INDEX = "https://pypi.org"
DEFAULT_TIMEOUT = 30
USER_AGENT = "textflowkit-release-fonts"
WHEEL_SUFFIX = ".whl"
SDIST_SUFFIX = ".tar.gz"
# The complete published set, per kind, and the index's own name for it. A third
# file of any other kind is refused rather than copied into the release.
EXPECTED_KINDS = ("wheel", "sdist")
PACKAGETYPES = {"wheel": "bdist_wheel", "sdist": "sdist"}
# PKG-INFO is generated by the builder and is not a file in the checkout, so it
# is the one sdist member that has no counterpart to compare against.
GENERATED_SDIST_MEMBERS = frozenset({"PKG-INFO"})
# Build debris and interpreter caches are not package source; everything else in
# the package directory is compared against the published sdist.
SKIPPED_DIRS = frozenset({
    ".git", ".mypy_cache", ".pytest_cache", ".ruff_cache", "__pycache__", "build", "dist",
})
SKIPPED_SUFFIXES = (".pyc", ".pyo")
VERSION = re.compile(r"\A[0-9][0-9A-Za-z.!+]*\Z")
SHA256 = re.compile(r"\A[0-9a-f]{64}\Z")
ENTRY_FIELDS = ("filename", "packagetype", "url", "digests", "size")


class FontsReleaseError(Exception):
    """A release-blocking condition, described for the operator."""


@dataclass(frozen=True)
class PublishedFile:
    """One file the index recorded for a published version."""

    filename: str
    kind: str
    url: str
    sha256: str
    size: int


@dataclass(frozen=True)
class Resolution:
    """What the release should do about the fonts package."""

    mode: str  # "new" or "reuse"
    version: str
    files: tuple[PublishedFile, ...] = ()


def declared_version(package_dir: Path) -> str:
    """The fonts version the package declares, read from its `pyproject.toml`."""
    path = package_dir / "pyproject.toml"
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise FontsReleaseError(f"cannot read {path}: {exc}") from exc
    try:
        import tomllib
    except ModuleNotFoundError as exc:  # Python < 3.11; the release runner is 3.12
        raise FontsReleaseError(f"reading {path} requires Python 3.11+ (tomllib)") from exc
    try:
        project = tomllib.loads(raw)["project"]
    except (tomllib.TOMLDecodeError, KeyError, TypeError) as exc:
        raise FontsReleaseError(f"{path} has no usable [project] table: {exc}") from exc
    if not isinstance(project, dict) or not isinstance(project.get("version"), str):
        raise FontsReleaseError(f"{path} declares no project version")
    version = project["version"]
    if not VERSION.match(version):
        raise FontsReleaseError(f"{path} declares version {version!r}, which is not a version")
    return version


def _index_url(index: str, project: str, version: str) -> str:
    if urllib.parse.urlsplit(index).scheme != "https":
        raise FontsReleaseError(f"the index must be read over https, got {index!r}")
    return f"{index.rstrip('/')}/pypi/{urllib.parse.quote(project)}/{urllib.parse.quote(version)}/json"


def _read_json(url: str, opener, timeout: int) -> object | None:
    """Return the decoded response, or None when the index answers 404."""
    request = urllib.request.Request(url, headers={
        "Accept": "application/json",
        "User-Agent": USER_AGENT,
    })
    try:
        with opener(request, timeout=timeout) as response:
            status = getattr(response, "status", 200)
            raw = response.read()
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return None
        raise FontsReleaseError(f"the index answered HTTP {exc.code} for {url}") from exc
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        raise FontsReleaseError(f"cannot reach the index at {url}: {exc}") from exc
    if status != 200:
        raise FontsReleaseError(f"the index answered HTTP {status} for {url}")
    try:
        return json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise FontsReleaseError(f"the index response for {url} is not UTF-8 JSON: {exc}") from exc


def _identify(filename: str, project: str, version: str) -> str:
    """Return the kind a published filename claims, or refuse it."""
    if "/" in filename or "\\" in filename:
        raise FontsReleaseError(f"unexpected published file: {filename!r} is not a plain filename")
    if filename.endswith(WHEEL_SUFFIX):
        # `{distribution}-{version}(-{build})?-{python}-{abi}-{platform}.whl`
        fields = filename[: -len(WHEEL_SUFFIX)].split("-")
        if len(fields) < 5:
            raise FontsReleaseError(f"unexpected published file: {filename!r} is not a wheel name")
        raw, artifact_version, kind = fields[0], fields[1], "wheel"
    elif filename.endswith(SDIST_SUFFIX):
        raw, separator, artifact_version = filename[: -len(SDIST_SUFFIX)].rpartition("-")
        if not separator or not raw or not artifact_version:
            raise FontsReleaseError(f"unexpected published file: {filename!r} is not an sdist name")
        kind = "sdist"
    else:
        raise FontsReleaseError(
            f"unexpected published file: {filename!r} is neither a wheel nor an sdist"
        )
    if raw.replace("-", "_") != project.replace("-", "_"):
        raise FontsReleaseError(
            f"unexpected published file: {filename!r} is not a {project} file"
        )
    if artifact_version != version:
        raise FontsReleaseError(
            f"unexpected published file: {filename!r} is not a {project} {version} file "
            f"(its version field is {artifact_version})"
        )
    return kind


def _validate_url(url: str, filename: str) -> None:
    parts = urllib.parse.urlsplit(url)
    if parts.scheme != "https":
        raise FontsReleaseError(f"{filename}: {url!r} is not an https url")
    segments = parts.path.split("/")
    if any(segment in ("..", ".") for segment in segments):
        raise FontsReleaseError(f"{filename}: {url!r} escapes its directory")
    if not parts.netloc or segments[-1] != filename:
        raise FontsReleaseError(f"{filename}: {url!r} does not name the file it serves")


def published_files(payload: object, project: str, version: str) -> list[PublishedFile]:
    """The wheel and the sdist the index recorded, in that order, or refuse the release."""
    if not isinstance(payload, dict):
        raise FontsReleaseError("the index response is not a JSON object")
    entries = payload.get("urls")
    if not isinstance(entries, list):
        raise FontsReleaseError(f"the index response for {project} {version} has no urls list")
    found: dict[str, PublishedFile] = {}
    for raw in entries:
        if not isinstance(raw, dict):
            raise FontsReleaseError("the index returned a published file that is not an object")
        missing = [field for field in ENTRY_FIELDS if field not in raw]
        if missing:
            raise FontsReleaseError(
                f"the index returned a published file without {', '.join(missing)}"
            )
        filename = raw["filename"]
        if not isinstance(filename, str):
            raise FontsReleaseError("the index returned a published file without a name")
        kind = _identify(filename, project, version)
        if raw["packagetype"] != PACKAGETYPES[kind]:
            raise FontsReleaseError(
                f"{filename}: the index calls it {raw['packagetype']!r}, not "
                f"{PACKAGETYPES[kind]!r}"
            )
        digests = raw["digests"]
        digest = digests.get("sha256") if isinstance(digests, dict) else None
        if not isinstance(digest, str) or not SHA256.match(digest):
            raise FontsReleaseError(f"{filename}: the index recorded no usable sha256 digest")
        size = raw["size"]
        if not isinstance(size, int) or isinstance(size, bool) or size <= 0:
            raise FontsReleaseError(f"{filename}: the index recorded no usable size")
        url = raw["url"]
        if not isinstance(url, str):
            raise FontsReleaseError(f"{filename}: the index recorded no download url")
        _validate_url(url, filename)
        if kind in found:
            raise FontsReleaseError(
                f"duplicate published file: {filename} repeats the {kind} already "
                f"published as {found[kind].filename}"
            )
        found[kind] = PublishedFile(filename, kind, url, digest, size)
    missing = [kind for kind in EXPECTED_KINDS if kind not in found]
    if missing:
        raise FontsReleaseError(
            f"{project} {version} is published without its {', '.join(missing)}; a partial "
            f"publication cannot be reused, and its version cannot be published again"
        )
    return [found[kind] for kind in EXPECTED_KINDS]


def _download(entry: PublishedFile, staging: Path, opener, timeout: int) -> Path:
    request = urllib.request.Request(entry.url, headers={
        "Accept": "application/octet-stream",
        "User-Agent": USER_AGENT,
    })
    target = staging / entry.filename
    digest = hashlib.sha256()
    size = 0
    try:
        with opener(request, timeout=timeout) as response:
            status = getattr(response, "status", 200)
            if status != 200:
                raise FontsReleaseError(f"{entry.filename}: the index answered HTTP {status}")
            with target.open("wb") as handle:
                for chunk in iter(lambda: response.read(1024 * 1024), b""):
                    handle.write(chunk)
                    digest.update(chunk)
                    size += len(chunk)
    except urllib.error.HTTPError as exc:
        raise FontsReleaseError(
            f"{entry.filename}: HTTP {exc.code} from {entry.url}"
        ) from exc
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        raise FontsReleaseError(f"{entry.filename}: cannot download {entry.url}: {exc}") from exc
    if size != entry.size:
        raise FontsReleaseError(
            f"{entry.filename}: downloaded {size} bytes, but the index recorded "
            f"{entry.size}; the download is partial"
        )
    actual = digest.hexdigest()
    if actual != entry.sha256:
        raise FontsReleaseError(
            f"{entry.filename}: SHA-256 {actual} does not match the SHA-256 "
            f"{entry.sha256} the index recorded"
        )
    _verify_archive(target, entry.kind)
    return target


def _verify_archive(path: Path, kind: str) -> None:
    """A matching digest is not enough: the file must open as its own format."""
    try:
        if kind == "sdist":
            with tarfile.open(path) as archive:
                archive.getnames()
        else:
            with zipfile.ZipFile(path) as archive:
                archive.namelist()
    except (tarfile.TarError, zipfile.BadZipFile, OSError) as exc:
        raise FontsReleaseError(f"{path.name}: is not a readable {kind}: {exc}") from exc


def _digest_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def published_source(sdist: Path) -> dict[str, str]:
    """The sdist's payload as `relative path -> sha256`, without generated members."""
    try:
        with tarfile.open(sdist) as archive:
            members = [member for member in archive.getmembers() if member.isfile()]
            roots = {member.name.split("/", 1)[0] for member in members}
            if len(roots) != 1:
                raise FontsReleaseError(
                    f"{sdist.name}: expected one top-level directory, found {sorted(roots)}"
                )
            root = f"{roots.pop()}/"
            source = {}
            for member in members:
                if not member.name.startswith(root):
                    raise FontsReleaseError(
                        f"{sdist.name}: {member.name} is outside {root}"
                    )
                relative = member.name[len(root):]
                if relative in GENERATED_SDIST_MEMBERS:
                    continue
                handle = archive.extractfile(member)
                if handle is None:
                    raise FontsReleaseError(f"{sdist.name}: cannot read {member.name}")
                source[relative] = hashlib.sha256(handle.read()).hexdigest()
    except tarfile.TarError as exc:
        raise FontsReleaseError(f"{sdist.name}: is not a readable sdist: {exc}") from exc
    return source


def local_source(package_dir: Path) -> dict[str, str]:
    """The working tree's package source as `relative path -> sha256`."""
    source = {}
    for path in sorted(package_dir.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(package_dir)
        if any(part in SKIPPED_DIRS for part in relative.parts[:-1]):
            continue
        if any(part.endswith(".egg-info") for part in relative.parts):
            continue
        if path.suffix in SKIPPED_SUFFIXES:
            continue
        source[relative.as_posix()] = _digest_of(path)
    if not source:
        raise FontsReleaseError(f"{package_dir} has no package source to compare")
    return source


def describe_drift(sdist: Path, package_dir: Path) -> list[str]:
    """Every way the working tree differs from the source the sdist published."""
    published = published_source(sdist)
    local = local_source(package_dir)
    problems = []
    for name in sorted(set(published) | set(local)):
        if name not in local:
            problems.append(f"{name} is in the published source but not in the working tree")
        elif name not in published:
            problems.append(f"{name} is in the working tree but not in the published source")
        elif local[name] != published[name]:
            problems.append(f"{name} has different bytes than the published source")
    return problems


def resolve(
    *,
    package_dir: Path,
    out_dir: Path,
    project: str = DEFAULT_PROJECT,
    index: str = DEFAULT_INDEX,
    version: str | None = None,
    timeout: int = DEFAULT_TIMEOUT,
    opener=None,
) -> Resolution:
    """Decide between reusing the published files and publishing a new version."""
    opener = opener or urllib.request.urlopen
    version = version if version is not None else declared_version(package_dir)
    payload = _read_json(_index_url(index, project, version), opener, timeout)
    if payload is None:
        return Resolution("new", version)
    entries = published_files(payload, project, version)
    staging = Path(tempfile.mkdtemp(prefix="textflowkit-fonts-"))
    try:
        fetched = {entry.kind: _download(entry, staging, opener, timeout) for entry in entries}
        problems = describe_drift(fetched["sdist"], package_dir)
        if problems:
            raise FontsReleaseError(
                f"{package_dir} does not match the source published as {project} {version}: "
                + "; ".join(problems)
                + f"; bump the version in {package_dir / 'pyproject.toml'} so the change is "
                "published, or revert it"
            )
        out_dir.mkdir(parents=True, exist_ok=True)
        for entry in entries:
            os.replace(fetched[entry.kind], out_dir / entry.filename)
    finally:
        shutil.rmtree(staging, ignore_errors=True)
    return Resolution("reuse", version, tuple(entries))


def main(argv: list[str] | None = None, *, opener=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--package-dir", default=DEFAULT_PACKAGE_DIR,
                        help="the fonts package directory whose source is compared")
    parser.add_argument("--out-dir", default=DEFAULT_OUT_DIR,
                        help="where the verified published files are placed for reuse")
    parser.add_argument("--project", default=DEFAULT_PROJECT)
    parser.add_argument("--index-url", default=DEFAULT_INDEX)
    parser.add_argument("--version", default=None,
                        help="the declared fonts version, read from <package-dir>/pyproject.toml "
                             "when it is not given")
    parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT)
    parser.add_argument("--github-output", default=None,
                        help="append fonts_mode=<new|reuse> for the workflow job to publish")
    args = parser.parse_args(argv)
    if args.timeout <= 0:
        parser.error("--timeout must be positive")
    try:
        resolution = resolve(
            package_dir=Path(args.package_dir),
            out_dir=Path(args.out_dir),
            project=args.project,
            index=args.index_url,
            version=args.version,
            timeout=args.timeout,
            opener=opener,
        )
    except FontsReleaseError as exc:
        print(f"fonts release fetch failed: {exc}", file=sys.stderr)
        return 1
    if resolution.mode == "new":
        print(f"{args.project} {resolution.version} is not on {args.index_url} (HTTP 404): "
              f"a new fonts version, which the release will build and publish")
    else:
        print(f"{args.project} {resolution.version} is already published: reusing its "
              f"{len(resolution.files)} published files, verified against the index "
              f"(fonts_mode={resolution.mode})")
        for entry in resolution.files:
            print(f"  {entry.filename}  {entry.sha256}")
        print(f"{args.package_dir} matches the source published as "
              f"{args.project} {resolution.version}")
    if args.github_output:
        with Path(args.github_output).open("a", encoding="utf-8", newline="\n") as handle:
            handle.write(f"fonts_mode={resolution.mode}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
